name: starkeeper

services:
  identity-service:
    container_name: starkeeper_identity_service
    build:
      context: ./server
      dockerfile: Services/IdentityService/Dockerfile
      target: development
    ports:
      - "5000:${IDENTITY_API_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=${IDENTITY_API_URL}
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=${IDENTITY_API_URL}
      - ConnectionStrings__IdentityServiceContext=${IDENTITY_API_CONNECTION_STRING}
      - Rebus__RabbitMqConnectionString=${IDENTITY_API_REBUS_RABBITMQ_CONNECTION_STRING}
      - Rebus__UserCreatedQueue=${IDENTITY_API_REBUS_RABBITMQ_USER_CREATE_QUEUE}
    networks:
      - starkeeper_network
    depends_on:
      - identity-database
    volumes:
      - ./server/Services/IdentityService:/app/Services/IdentityService

  identity-database:
    container_name: starkeeper_identity_database
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${IDENTITY_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - identity-db-data:/var/lib/postgresql/data
    networks:
      - starkeeper_network

  bookmarks-web-app:
    container_name: starkeeper_bookmarks_web_app
    build:
      context: ./web/apps/bookmarks
      target: development
    ports:
      - 4000:${BOOKMARK_WEB_APP_PORT}
    networks:
      - starkeeper_network
    volumes:
      - ./web/apps/bookmarks:/src
      - /src/node_modules

  rabbit-mq:
    image: rabbitmq:3-management
    container_name: starkeeper_rabbitmq
    hostname: starkeeper_rabbitmq
    ports:
      - 5672:${RABBITMQ_PORT}
      - 15672:${RABBITMQ_MANAGEMENT_PORT}
    environment:
      - RABBITMQ_DEFAULT_USER:${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS:${RABBITMQ_PASSWORD}

volumes:
  identity-db-data:

networks:
  starkeeper_network:
    driver: bridge